services:
  rest-service:
    build:
      context: .
      dockerfile: ./deployment/docker/rest/Dockerfile
    ports:
      - "8001:8001"  # Host:8001 -> Container:8000 (REST API)
      - "8000:8000"  # Host:8000 -> Container:8002 (REST Metrics)
    volumes:
      - ./src:/app/src
      - ./proto:/app/proto
    networks:
      - benchmark-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - benchmark-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - benchmark-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - benchmark-network


networks:
  benchmark-network:
    driver: bridge

volumes:
  grafana-storage:
