services:
  grpc-service:
    build:
      context: .
      dockerfile: ./deployment/docker/grpc/Dockerfile
    ports:
      - "50051:50051"  # Host:50051 -> Container:50051 (gRPC API)
      - "8181:8181"    # Host:8002 -> Container:8002 (gRPC Metrics)
    volumes:
      - ./src:/app/src
      - ./proto:/app/proto
    networks:
      - benchmark-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9191:9191"
    volumes:
      - ./deployment/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - benchmark-network

  grafana:
    image: grafana/grafana
    ports:
      - "3131:3131"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - benchmark-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9101:9101"
    networks:
      - benchmark-network


networks:
  benchmark-network:
    driver: bridge

volumes:
  grafana-storage:
