global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape REST Service
  - job_name: "rest-service"
    static_configs:
      - targets: ["rest-service:8000"]
    metrics_path: "/metrics"

  # Scrape gRPC Service
  - job_name: "grpc-service"
    static_configs:
      - targets: ["grpc-service:8002"]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
